import { mkdir, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { CONFIG } from "./config.js";
import type { DraftedPost } from "./compose.js";

const run = promisify(execFile);
const DRAFTS_ROOT = new URL(`../${CONFIG.draftsDir}/`, import.meta.url);

function stamp(now: Date): string {
  return now.toISOString().slice(0, 10); // YYYY-MM-DD
}

/** Write the draft to drafts/YYYY-MM-DD-update.md and (optionally) commit+push. */
export async function writeDraft(post: DraftedPost, now = new Date()): Promise<string> {
  await mkdir(DRAFTS_ROOT, { recursive: true });
  const date = stamp(now);
  const fileUrl = new URL(`${date}-update.md`, DRAFTS_ROOT);
  const filePath = decodeURIComponent(fileUrl.pathname.replace(/^\/([A-Za-z]:)/, "$1"));

  const doc = [
    `# Percolator update — ${date}`,
    ``,
    `> Draft X thread — review, edit, then post manually. Generated by dcc-watch.`,
    ``,
    `## Thread`,
    ``,
    post.thread,
    ``,
    `---`,
    ``,
    `<details><summary>Source digest (for review — not posted)</summary>`,
    ``,
    "```",
    post.digest,
    "```",
    ``,
    `</details>`,
    ``,
  ].join("\n");

  await writeFile(fileUrl, doc, "utf8");
  console.log(`[draft] wrote ${filePath}`);

  if (CONFIG.gitCommitDrafts) {
    try {
      const cwd = decodeURIComponent(new URL("../", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"));
      await run("git", ["add", `${CONFIG.draftsDir}/${date}-update.md`], { cwd });
      await run("git", ["commit", "-m", `draft: Percolator update ${date}`], { cwd });
      await run("git", ["push"], { cwd });
      console.log(`[draft] committed + pushed ${date}-update.md`);
    } catch (err) {
      console.error("[draft] git commit/push failed (draft is still on disk):", (err as Error).message);
    }
  }

  return filePath;
}
